version: '3'

services:
  flask:
    build: .
    image: pythondocker:0.0.1
    container_name: flask
    env_file:
      - env.conf
    ports:
      - "5000:5000"
    networks:
      - flask
networks:
  flask:
